[project]
name = "backend"
version = "0.1.0"
description = "RSS Feed Generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=6.2.4",
    "fastapi>=0.124.4",
    "psycopg[binary]>=3.3.2",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]
